databases:
  - name: Portfoliodb
    plan: free
    databaseName: Portfolio
    user: Portfolio

services:
  - type: web
    plan: free
    name: Portfolio
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn Portfolio.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Portfoliodb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4