databases:
  - name: portfoliodb
    plan: free
    databaseName: portfolio
    user: portfolio

services:
  - type: web
    name: portfolio
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "cd Portfolio && gunicorn Portfolio.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfoliodb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
